name: yuk_main
description: "Booking lapanganmu disini."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  flutter:
    sdk: flutter
  flutter_map: ^6.1.0
  flutter_rating_bar: ^4.0.1
  geolocator: ^10.1.1
  http: ^1.2.1
  image_picker: ^1.0.7
  latlong2: ^0.9.1
  location_picker_flutter_map: ^3.0.1
  modal_bottom_sheet: ^3.0.0
  permission_handler: ^11.3.1
  photo_view: ^0.14.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
